#!/bin/bash

if [[ (("${#SERNUM}"> 11)) ]]; then
SERIAL=$( echo $SERNUM | tail -c 5 )
DEVICE_SERIAL_CURL=$(curl -s "https://support-sp.apple.com/sp/product?cc=$SERIAL")
DEVICE_YEAR=$( echo $DEVICE_SERIAL_CURL | grep -o 'Early\|Mid\|Late\|20[^',']*' | tr -d '[:space:]' | tr -d ')' | sed 's/20/0/g' | sed 's/Early0/D/g' | sed 's/Mid0/M/g' | sed 's/Late0/F/g' | cut -f1 -d "<")
  if [[ "$DEVICE_YEAR" == "00" ]]; then
    DEVICE_YEAR="020"
  elif [ -z $DEVICE_YEAR ]; then
    DEIVCE_IDENTIFIER=$(sysctl hw.model | awk '{print $NF}')
    DEVICE_MODEL_CURL=$(curl -s "https://raw.githubusercontent.com/Trush182/mac-models/main/models" | grep "|$DEIVCE_IDENTIFIER\| \+\$DEIVCE_IDENTIFIER" | cut -f1 -d"|")
    DEVICE_YEAR=$( echo "$DEVICE_MODEL_CURL" | grep -o 'Early\|Mid\|Late\|20[^',']*' | tr -d '[:space:]' | tr -d ')' | sed 's/20/0/g' | sed 's/Early0/D/g' | sed 's/Mid0/M/g' | sed 's/Late0/F/g' )
    if [[ (("${#DEVICE_YEAR}" > 3)) ]]; then
      DEVICE_YEAR=$( echo $DEVICE_YEAR | sed 's/\(.\{3\}\)/\1 /g' | sed 's/0/20/g' | sed 's/D/Early0/g' | sed 's/M/Mid0/g' | sed 's/F/Late0/g' | awk '{$1=$1" ou"}1')
    fi
  elif [ -z $DEVICE_YEAR ]; then
    DEVICE_YEAR="nil"
  fi
elif [[ (("${#SERNUM}" < 11)) ]]; then
SERNUM="00$SERNUM"
DEIVCE_IDENTIFIER=$(sysctl hw.model | awk '{print $NF}')
DEVICE_MODEL_CURL=$(curl -s "https://raw.githubusercontent.com/Trush182/mac-models/main/models" | grep "|$DEIVCE_IDENTIFIER\| \+\$DEIVCE_IDENTIFIER" | cut -f1 -d"|")
  if [[ $DEVICE_MODEL_CURL = *"("*")"* ]]; then
    DEVICE_MODEL=$( echo $DEVICE_MODEL_CURL | cut -f1 -d"|" )	
    DEVICE_YEAR=$( echo "$DEVICE_MODEL" | grep -o 'Early\|Mid\|Late\|20[^',']*' | tr -d '[:space:]' | tr -d ')' | sed 's/20/0/g' | sed 's/Early0/D/g' | sed 's/Mid0/M/g' | sed 's/Late0/F/g' )
  elif [ -z $DEVICE_MODEL_CURL ]; then
  DEVICE_MODEL_CURL=$(curl -s "https://raw.githubusercontent.com/Trush182/mac-models/main/models" | grep "$DEIVCE_IDENTIFIER" | cut -f1 -d"|")
  #   DEVICE_YEAR=$( echo "$DEVICE_MODEL" | grep -o -E '[0-9][0-9][0-9][0-9]' )
  elif [[ "$DEVICE_YEAR" == "00" ]]; then
  DEVICE_YEAR="020"
    if [[ (("${#DEVICE_YEAR}" > 3)) ]]; then
      DEVICE_YEAR=$( echo $DEVICE_YEAR | sed 's/\(.\{3\}\)/\1 /g' | sed 's/0/20/g' | sed 's/D/Early0/g' | sed 's/M/Mid0/g' | sed 's/F/Late0/g' | awk '{$1=$1" ou"}1')
    fi
    elif [ -z $DEVICE_YEAR ]; then
    DEVICE_YEAR="nil"
  fi
fi

echo "$DEVICE_YEAR"
